# Generated by Django 3.2.1 on 2021-05-12 09:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendSubForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('surname', models.CharField(max_length=25, verbose_name='surname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('organization', models.CharField(max_length=60, verbose_name='organization')),
                ('position', models.CharField(max_length=60, verbose_name='position')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('post_code_city', models.CharField(max_length=60, verbose_name='post_code_city')),
                ('postal_address', models.CharField(max_length=100, verbose_name='postal_address')),
                ('web_site', models.CharField(max_length=40, verbose_name='web_site')),
                ('fax', models.CharField(max_length=60, verbose_name='fax')),
                ('institute', models.CharField(max_length=100, verbose_name='institute')),
                ('abstract_title', models.CharField(max_length=100, verbose_name='abstract_title')),
                ('upload_abstract', models.FileField(upload_to='uploads/', verbose_name='upload_abstract')),
                ('talk_s', models.CharField(max_length=5, verbose_name='talk')),
                ('section', models.CharField(max_length=40, verbose_name='section')),
                ('invitation_s', models.CharField(max_length=5, verbose_name='invitation')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
