# Generated by Django 3.2.1 on 2021-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsubform',
            name='invitation_s',
            field=models.CharField(max_length=6, verbose_name='invitation'),
        ),
        migrations.AlterField(
            model_name='sendsubform',
            name='talk_s',
            field=models.CharField(max_length=3, verbose_name='talk'),
        ),
    ]
