# Generated by Django 3.2.1 on 2021-05-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210512_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendSubForm',
            new_name='SendSubmission',
        ),
    ]
