# Generated by Django 3.2.1 on 2021-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_sendsubform_sendsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('choice', models.CharField(max_length=6)),
                ('file', models.FileField(upload_to='filess/')),
            ],
        ),
    ]
