# Generated by Django 3.2.1 on 2021-05-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
