# Generated by Django 3.2.1 on 2021-05-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsubmission',
            name='invitation_s',
        ),
    ]
