# Generated by Django 3.2.1 on 2021-05-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_sendsubmission_invitation_s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
