# Generated by Django 3.2.1 on 2021-05-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsubmission',
            name='talk_s',
            field=models.CharField(max_length=6, verbose_name='talk'),
        ),
    ]
