# Generated by Django 3.2.1 on 2021-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_sendsubmission_talk_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.CharField(max_length=20),
        ),
    ]
