# Generated by Django 3.2.1 on 2021-05-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210521_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsubmission',
            name='upload_abstract',
        ),
    ]
