# Generated by Django 3.2.1 on 2021-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210521_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsubmission',
            name='upload_abstract',
            field=models.FileField(upload_to='uploads/', verbose_name='upload_abstract'),
        ),
    ]
