# Generated by Django 3.2.1 on 2021-05-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_sendsubmission_upload_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(upload_to='kk/'),
        ),
    ]
