# Generated by Django 3.2.1 on 2021-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ch'),
        ),
    ]
