# Generated by Django 3.2.1 on 2021-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_test_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsubmission',
            name='talk_s',
            field=models.CharField(default='unsignet', max_length=6, verbose_name='talk'),
        ),
    ]
