# Generated by Django 3.2.1 on 2021-05-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_sendsubmission_talk_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsubmission',
            name='invitation_s',
            field=models.CharField(default='unsignet', max_length=6, verbose_name='Do you need a letter of invitation:'),
        ),
        migrations.AlterField(
            model_name='sendsubmission',
            name='talk_s',
            field=models.CharField(default='unsignet', max_length=6, verbose_name='Do you have a talk'),
        ),
    ]
