# Generated by Django 3.2.1 on 2021-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210521_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsubmission',
            name='upload_abstract',
            field=models.FileField(upload_to='file/', verbose_name='upload_abstract'),
        ),
    ]
