# Generated by Django 3.2.1 on 2021-05-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_sendsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsubmission',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
