# Generated by Django 3.2.1 on 2021-05-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_sendsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsubmission',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
