# Generated by Django 3.2.1 on 2021-06-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_sendsubmission_send_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
